### PR TITLE
Fixed Root motion rotation glitch #23

### PR DESCRIPTION
**Pull request by gnuton**
Removed copy rotation constraints. Not sure if this is gonna break something.

Can this break something? 
@enziop if you have a few mins would you double check that this is right?  do you remember the reason why those constrains were added in the first place for the root bone?

### CODE REVIEW

**Comment by enziop** [comment]
The copy rotation constraints are needed to transfer the rotation from the hip to the new root.
If your character walks a curve, this is needed to do correct root motion.
if you disable it, your character might still turn in animation, but the root will always face the same direction an your characters forward vector will not follow the animation i guess
my semsester is now over and i can help checking why this glitch happens
it might also have to do with blenders fbx export, there are some conditions where the exprter breaks rotations, but this only hppened to me on the knees so far.

**Comment by gnuton** [comment]
Okay the problem seems to be (maybe)  a little more clear.
So if I got it right the fix should be something like this:
- root bone should take the hips rotation
- no hips-root relative rotation.
So the solutions is in implementing the second bullet

**Comment by gnuton** [comment]
I had another look at this problem.
I\ll add a few comments in #24 my previous statement is not right.

**Comment by enziop** [comment]
@gnuton can you make this pull request again with just the __init__ file?, the changes there look fine, even if i dont fully understand what the bpy locals and reload block exactly does
or how can i merge only one file from the pull request? is it possible via the github webpage or only with command line tools?

**Comment by gnuton** [comment]
Hey Ezio!
Sure. I ll try to do it this night.. I should check your new changes too.
Thanks again for your contributions..

**Pull request closed without merging**
